(require 'breadcrumb)

(autoload 'bc-set "breadcrumb" "Set bookmark in current point." t)
(autoload 'bc-previous "breadcrumb" "Go to previous bookmark." t)
(autoload 'bc-next "breadcrumb" "Go to next bookmark." t)
(autoload 'bc-local-previous "breadcrumb" "Go to previous local bookmark." t)
(autoload 'bc-local-next "breadcrumb" "Go to next local bookmark." t)
(autoload 'bc-goto-current "breadcrumb" "Go to the current bookmark." t)
(autoload 'bc-list "breadcrumb" "List all bookmarks in menu mode." t)
(autoload 'bc-clear "breadcrumb" "Clear all bookmarks." t)

(global-set-key (kbd "S-SPC") 'bc-set)
(global-set-key (kbd "M-j") 'bc-previous)
(global-set-key (kbd "M-S-j") 'bc-next)
(global-set-key (kbd "M-<up>") 'bc-local-previous)
(global-set-key (kbd "M-<down>") 'bc-local-next)
(global-set-key (kbd "C-c j") 'bc-goto-current)
(global-set-key (kbd "C-x M-j") 'bc-list)
